gaana/urls.py
from django.urls import path
from . import views

app_name = 'gaana'

urlpatterns = [
    path('', views.home , name='home'),
    path('<int:albumid>/songs/' , views.index , name="index"),
    path('<int:playlistid>/playlist/' , views.index_playlist , name="index_playlist"),
    path('playlist/<playlist_id>', views.index_playlist_spotify, name='playlist_detail'),


    # path('song/',views.song , name="song")
]

music/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from gaana.views import (song,
                        player_song_view,
                        player_album_selected,
                        modal_open,add_to_playlist,
                        playlist_selected,
                        add_playlist_basic,
                        re_render_playlist,
                        follow_artist,
                        follow_user,
                        search_user,
                        search_song,
                        refresh_user_list,
                        refresh_search_list,
                        showfolloweduserplaylist,
                        showfolloweduserSongs,
                        SaveFollowedUserPlaylist,
                        recently_played,
                        radio,
                        song_playlist_song,
                        song_player_playlist,
                        re_render_user_followed_playlist,
                        search_homepage,
                        search_artist_homepage)
from music import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name="home"),
    path('music/',include('gaana.urls')),

    # AJAX VIEW
    path('song/',song , name="song"),
    path('song_player/',player_song_view , name="song_player"),
    path('song_selected_album/',player_album_selected , name="album_selected"),
    path('display_modal/',modal_open , name="modal_open"),
    path('add_to_playlist/',add_to_playlist , name="add_to_playlist"),
    path('playlist_selected/',playlist_selected , name="playlist_selected"),
    path('add_playlist_basic/',add_playlist_basic , name="add_playlist_basic"),
    path('re_render_playlist/',re_render_playlist , name="re_render_playlist"),
    path('follow_artist/',follow_artist , name="follow_artist"),
    path('follow_user/',follow_user , name="follow_user"),
    path('search_user/',search_user , name="search_user"),
    path('refresh_user_list/',refresh_user_list , name="refresh_user_list"),
    path('refresh_search_list/',refresh_search_list , name="refresh_search_list"),
    path('showfolloweduserplaylist/',showfolloweduserplaylist , name="showfolloweduserplaylist"),
    path('showfolloweduserSongs/',showfolloweduserSongs , name="showfolloweduserSongs"),
    path('SaveFollowedUserPlaylist/',SaveFollowedUserPlaylist , name="SaveFollowedUserPlaylist"),
    path('recently_played/',recently_played , name="recently_played"),
    path('radio/',radio,name="radio"),
    path('search_song/',search_song , name="search_song"),
    path('song_playlist_song/',song_playlist_song , name="song_playlist_song"),
    path('song_player_playlist/',song_player_playlist , name="song_player_playlist"),
    path('re_render_user_followed_playlist/',re_render_user_followed_playlist, name="re_render_user_followed_playlist"),
    path('search_homepage/',search_homepage , name="search_homepage"),
    path('remove_modal/',views.remove_modal,name="remove_modal"),
    path('search_artist_homepage/',search_artist_homepage , name="search_artist_homepage"),










    #AJAX VIEWS END
    path('users/',include('users.urls')),
    path('', include('spotify_app.urls', namespace='spotify_app')),
    path('social/', include('social_django.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
# from users.views import ArtistSignUpView



app_name = 'users'

urlpatterns = [
    path('login/', views.login_customer, name='login'),
    path('register/', views.register_customer, name='register'),
    path('logout/', views.logout_customer , name='logout'),
    path('artist/',views.artist_view , name='home'),
    path('artist/add',views.add_album , name='add_album'),
    path('artist/song/<int:albumid>/add',views.add_song , name='add_song'),
    path('choose/',views.choose_user_type , name='choose_user_type'),
    path('signup/artist/', views.register_artist, name='artist_signup'),


    # path('dashboard/', views.dashboard_customer , name='dashboard'),
    # path('<int:user_id>/profile/', views.profile_customer , name='profile'),
    # path('signup/artist/', ArtistSignUpView.as_view(), name='artist_signup'),
    # path('accounts/signup/student/', StudentSignUpView.as_view(), name='student_signup'),
    path('artist/song/<int:albumid>',views.artist_view_song , name='song_detail'),
    # path('myposts/', views.myposts , name='myposts'),
]

templates/artist/add.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="/static/assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="/static/assets/img/favicon.png">
  <title>
Songify
  </title>
  <!-- Extra details for Live View on GitHub Pages -->
  <!-- Canonical SEO -->
  <link rel="canonical" href="https://www.creative-tim.com/product/argon-design-system" />
  <!--  Social tags      -->
  <meta name="keywords" content="design system, bootstrap 4 design system, bootstrap 4 design, bootstrap 4 system, bootstrap 4, bootstrap 4 uit kit, bootstrap 4 kit, argon, argon ui kit, creative tim, html kit, html css template, web template, bootstrap, bootstrap 4, css3 template, frontend, responsive bootstrap template, bootstrap ui kit, responsive ui kit, argon design system">
  <meta name="description" content="Start your development with a Design System for Bootstrap 4.">
  <!-- Schema.org markup for Google+ -->
  <meta itemprop="name" content="Argon - Free Design System for Bootstrap 4 by Creative Tim">
  <meta itemprop="description" content="Start your development with a Design System for Bootstrap 4.">
  <meta itemprop="image" content="https://s3.amazonaws.com/creativetim_bucket/products/90/original/opt_argon_thumbnail.jpg">
  <!-- Twitter Card data -->
  <meta name="twitter:card" content="product">
  <meta name="twitter:site" content="@creativetim">
  <meta name="twitter:title" content="Argon - Free Design System for Bootstrap 4 by Creative Tim">
  <meta name="twitter:description" content="Start your development with a Design System for Bootstrap 4.">
  <meta name="twitter:creator" content="@creativetim">
  <meta name="twitter:image" content="https://s3.amazonaws.com/creativetim_bucket/products/90/original/opt_argon_thumbnail.jpg">
  <!-- Open Graph data -->
  <meta property="fb:app_id" content="655968634437471">
  <meta property="og:title" content="Argon Design System by Creative Tim" />
  <meta property="og:type" content="article" />
  <meta property="og:url" content="https://demos.creative-tim.com/argon-design-system/index.html" />
  <meta property="og:image" content="https://s3.amazonaws.com/creativetim_bucket/products/90/original/opt_argon_thumbnail.jpg" />
  <meta property="og:description" content="Start your development with a Design System for Bootstrap 4." />
  <meta property="og:site_name" content="Creative Tim" />
  <!--  -->
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  <!-- Nucleo Icons -->
  <link href="/static/assets/css/nucleo-icons.css" rel="stylesheet" />
  <link href="/static/assets/css/nucleo-svg.css" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <link href="/static/assets/css/font-awesome.css" rel="stylesheet" />
  <link href="/static/assets/css/nucleo-svg.css" rel="stylesheet" />
  <!-- CSS Files -->
  <link href="/static/assets/css/argon-design-system.min.css?v=1.2.0" rel="stylesheet" />
  <!-- Google Tag Manager -->

  <!-- End Google Tag Manager -->

  <style>
input[type="file"] {
    display: none;
}
.form-group{
    margin-bottom:20px !important;
}

.custom-file-upload {
    color: #fff;
    background-color: #5e72e4;
    border-color: #5e72e4;
    box-shadow: 0 4px 6px rgba(50, 50, 93, .11), 0 1px 3px rgba(0, 0, 0, .08);
    border: 1px solid #ccc;
    display: inline-block;
    padding: 6px 12px;
    cursor: pointer;

    font-weight: 600;

    text-align: center;
    vertical-align: middle;
    user-select: none;


    padding: .625rem 1.25rem;
    line-height: 1.5;
    border-radius: .25rem;
    transition: all .15s ease;
}

}
  </style>
</head>

<body class="login-page">
  <!-- Extra details for Live View on GitHub Pages -->
  <!-- Google Tag Manager (noscript) -->
  <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NKDMSK6" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
  <!-- End Google Tag Manager (noscript) -->
  <!-- Navbar -->
  <nav id="navbar-main" class="navbar navbar-main navbar-expand-lg navbar-transparent navbar-light headroom">
    <div class="container">
      <a class="navbar-brand mr-lg-5" href="{% url 'users:home' %}">
        {% comment %} <img src="/static/assets/img/brand/white.png"> {% endcomment %}
		Songify
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar_global" aria-controls="navbar_global" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse" id="navbar_global">
        <div class="navbar-collapse-header">
          <div class="row">
            <div class="col-6 collapse-brand">
              <a href="../../../index.html">
                <!--<img src="/static/assets/img/brand/blue.png">-->
                Songify
              </a>
            </div>
            <div class="col-6 collapse-close">
              <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar_global" aria-controls="navbar_global" aria-expanded="false" aria-label="Toggle navigation">
                <span></span>
                <span></span>
              </button>
            </div>
          </div>
        </div>
        <ul class="navbar-nav navbar-nav-hover align-items-lg-center">

          <!--<li class="nav-item dropdown">-->
          <!--  <a href="#" class="nav-link" data-toggle="dropdown" href="#" role="button">-->
          <!--    <i class="ni ni-collection d-lg-none"></i>-->
          <!--    <span class="nav-link-inner--text">Examples</span>-->
          <!--  </a>-->
          <!--  <div class="dropdown-menu">-->
          <!--    <a href="../examples/landing.html" class="dropdown-item">Landing</a>-->
          <!--    <a href="../examples/profile.html" class="dropdown-item">Profile</a>-->
          <!--    <a href="../examples/login.html" class="dropdown-item">Login</a>-->
          <!--    <a href="../examples/register.html" class="dropdown-item">Register</a>-->
          <!--  </div>-->
          <!--</li>-->
        </ul>

      </div>
    </div>
  </nav>
  <!-- End Navbar -->
  <section class="section section-shaped section-lg">
    <div class="shape shape-style-1 bg-gradient-default">
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
    </div>
    <div class="container pt-lg-7">
      <div class="row justify-content-center">
        <div class="col-lg-5">
          <div class="card bg-secondary shadow border-0">
            <div class="card-header bg-white pb-5">

            <div class="card-body px-lg-5 py-lg-5">
              <div class="text-center text-muted mb-4">
                <medium>Wanna Add a Cool Album?</medium>
              </div>
              <form  method="POST" enctype="multipart/form-data">
				{%csrf_token%}
                <div class="form-group mb-3">
                  <div class="input-group input-group-alternative">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="far fa-envelope"></i></span>
                    </div>
                    <input class="form-control" placeholder="Album Title" type="text" name="title">
                  </div>
                </div>
				     <div class="form-group mb-3">
                  <div class="input-group input-group-alternative">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="far fa-envelope"></i></span>
                    </div>
                    <input class="form-control" placeholder="A Lil Description" type="text" name="description">
                  </div>
                </div>



                <div class="form-group" id="cat1">
                {% if category %}
            {% comment %} <label for="sel1">Select category:</label> {% endcomment %}
            <select  name="category1" class="form-control" onchange='javascript:{document.getElementById("category").value=document.getElementById("sel1").options[document.getElementById("sel1").selectedIndex].value;}' id="sel1">
                <option disabled selected>--Select Category--</option>
                {%for cat in category%}
                    <option value="{{cat}}">{{cat}}</option>
                {%endfor%}
            </select>
            <input type="hidden" name="category" id="category">
            {% endif %}
            </div>
				   <div class="form-group focused">
                  <div class="input-group input-group-alternative ">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="fas fa-unlock-alt"></i></span>
                    </div>
                    <div class="justify-content-center">
                    <label class="custom-file-upload justify-content-center " id="image_input" placeholder="COVER PIC">
COVER PIC
                <input  type="file" name="image" class="form-control text-center" style="">
</label>
</div>
                  </div>

                </div>



                <div class="text-center">
                  <button type="submit" class="btn btn-primary my-4">CREATE</button>
                </div>
              </form>
            </div>
          </div>
          <div class="row mt-3">

          </div>
        </div>
      </div>
    </div>
  </section>

  <!--   Core JS Files   -->
  <script src="/static/assets/js/core/jquery.min.js" type="text/javascript"></script>
  <script src="/static/assets/js/core/popper.min.js" type="text/javascript"></script>
  <script src="/static/assets/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="/static/assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
  <!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
  <script src="/static/assets/js/plugins/bootstrap-switch.js"></script>
  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="/static/assets/js/plugins/nouislider.min.js" type="text/javascript"></script>
  <script src="/static/assets/js/plugins/moment.min.js"></script>
  <script src="/static/assets/js/plugins/datetimepicker.js" type="text/javascript"></script>
  <script src="/static/assets/js/plugins/bootstrap-datepicker.min.js"></script>
  <!-- Control Center for Argon UI Kit: parallax effects, scripts for the example pages etc -->
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
  <!-- Place this tag in your head or just before your close body tag. -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>
  <script src="/static/assets/js/argon-design-system.min.js?v=1.2.0" type="text/javascript"></script> <!-- Sharrre libray -->
  <script src="/static/assets/demo/jquery.sharrre.js"></script>
  <script>
    $(document).ready(function() {



      // Goolge Analytics Code Don't Delete

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-46172202-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script');
        ga.type = 'text/javascript';
        ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(ga, s);
      })();

      // Facebook Pixel Code Don't Delete
      ! function(f, b, e, v, n, t, s) {
        if (f.fbq) return;
        n = f.fbq = function() {
          n.callMethod ?
            n.callMethod.apply(n, arguments) : n.queue.push(arguments)
        };
        if (!f._fbq) f._fbq = n;
        n.push = n;
        n.loaded = !0;
        n.version = '2.0';
        n.queue = [];
        t = b.createElement(e);
        t.async = !0;
        t.src = v;
        s = b.getElementsByTagName(e)[0];
        s.parentNode.insertBefore(t, s)
      }(window,
        document, 'script', '//connect.facebook.net/en_US/fbevents.js');

      try {
        fbq('init', '111649226022273');
        fbq('track', "PageView");

      } catch (err) {
        console.log('Facebook Track Error:', err);
      }


      //
      //

    });
  </script>
  <noscript>
    <img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=111649226022273&ev=PageView&noscript=1" />
  </noscript>
  <script src="https://cdn.trackjs.com/agent/v3/latest/t.js"></script>
  <script>
    window.TrackJS &&
      TrackJS.install({
        token: "ee6fab19c5a04ac1a32a645abde4613a",
        application: "argon-design-system-pro"
      });
  </script>
</body>

</html>

templates/artist/product_detail.html
{% extends "base.html" %}


{% block title %}
    Update Products
{% endblock title %}

{% block content %}
 <div class="col-md-6 container">
        <form action="{% url "users:product_detail" product.productid%}" method="POST" enctype="multipart/form-data">

                {% csrf_token %}


        <div class="col-md-6 float-left" >

           <div class="form-group">
                <label>Product Name</label>
                <input type="text" name="title" value="{{ product.title }}" class="form-control-plaintext" readonly >
            </div>

            <div class="form-group">
                <label>Price</label>
                <input type="number" name="price" value="{{product.price}}" class="form-control" >
            </div>
            <div class="form-group">
                <label>Description</label>
                <input type="text" name="description" value="{{product.description}}" class="form-control" >
            </div>
            <div class="form-group">
                <label>Quantity</label>
                <input type="number" name="quantity" value="{{ product.quantity }}" class="form-control" >
            </div>
            <div class="form-group">
                <label>Category</label>
                <input type="text" name="category" class="form-control-plaintext" value="{{ product.category }}"  readonly >
            </div>
            <!-- <div class="form-group" >
                <label>Published at</label>
                <input id="date" type="datetime-local"  name="description" value="{{ product.published_at }}"  class="form-control" readonly>
            </div> -->
            <!-- <div class="form-group" >
                <label>ADD PRODUCT PICTURE</label>
                <input type="file" name="image" class="fomr-control">
            </div> -->

        </div>

        <div class="col-md-6 float-right">
             <div>
                <img src="{{product.photo.url}}" class="img-thumbnail" alt="">
            </div> 
            
        </div>

        <div class="form-group" style="width: fit-content;">
            <input type="submit" value="UPDATE PRODUCT"  class="btn btn-dark btn-block">
        </div>

        </form>
    </div>

    <script>
   document.getElementById('date').value = (new Date()).format("m/dd/yy");
</script>
    {% endblock content %}

templates/artist/sellerorder.html
{% extends "base.html" %}

{% comment %} {%for orders in order_seller%} {% endcomment %}
{% comment %} {{x}} {% endcomment %}

{% block title %}
    {{title|upper}}
{% endblock title %}



{% block content %}

  <div class="col-md-12 mt-5">
  	<h1 class="text-center">My Orders</h1>
	 <table class="table table-hover table-inverse">
	 	<thead>
	 		<tr>
                <th>Order ID</th>
	 			<th>Item Name</th>
                <th>Price</th>
	 			<th>Quantity</th>
	 			<th>Total</th>
                <th>Customer Name</th>
	 			<th>Customer Phone</th>
                <th>Customer Address</th>
	 			<th>Customer Email</th>
                <th>Order Status</th>

	 		</tr>
	 	</thead>
	 	<tbody>
	 		{% for ord in Order %}
                {%for orders in ord%}
				<tr>
					<td>{{orders.id}}</td>
					<td>{{orders.item}}</td>
					<td>{{orders.price}}</td>
					<td>{{orders.quantity}}</td>
                    <td>{{orders.total}}</td>
                    <td>{{orders.name}}</td>
                    <td>{{orders.phone}}</td>
					<td>{{orders.address}}</td>
					<td>{{orders.email}}</td>
					{% if orders.delivery  %}
						<td>Delivered</td>
					{% else %}
					   <td>Delivery Pending<br>
					    <a type="button" class="btn btn-info" href="{% url 'users:order_deliver' orders.id %}">Done</a></td>
					{% endif %}
				</tr>
                {%endfor%}
            {%endfor%}
	 	</tbody>
	 </table>
  </div>




{% endblock content %}





{% comment %} {% for ord in order %}
    {%for orders in ord%}
        {% comment %} {%for i in orders%}
    {{i.id}}
    {%endfor%} {% endcomment %}
    {% comment %} ID :{{orders.id}}
    <br>
    ITEM: {{orders.item}}

    <br> {% endcomment %}

{% comment %} {%endfor%}
{%endfor%} {% endcomment %}

{% comment %} {%endfor%} {% endcomment %}